backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use backend\models\Admin;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;
use backend\models\User;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index','profile'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        $links = [
            ['label' => 'Pages', 'url' => ['/page/index'],'description' => 'Manage pages'],
            ['label' => 'Blogs', 'url' => ['/blog'],'description' => 'Manage Subscribers'],
            ['label' => 'Testimonials', 'url' => ['/testimonial/index'],'description' => 'Manage testimonials'],
            ['label' => 'Culture and History', 'url' => ['/culture-and-history/index'],'description' => 'Manage Culture and History'],
            ['label' => 'Galleries', 'url' => ['/gallery/index'],'description' => 'Manage Galleries'],
            ['label' => 'Subscribers', 'url' => ['/subscriber/index'],'description' => 'Manage Subscribers'],
            ['label' => 'Instructors', 'url' => ['/instructor/index'],'description' => 'Manage Instructors'],
            ['label' => 'News And Events', 'url' => ['/news-and-event/index'],'description' => 'News And Events'],
            ['label' => 'Blocks', 'url' => ['/block/index'],'description' => 'Manage blocks'],
        ];

        return $this->render('index',[
            'links' => $links,
        ]);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionProfile($id)
    {
        $model = Admin::findOne($id);
        $model->scenario = 'update';

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                $model->generateTokens();
                if ($model->save(false)) {
                    Yii::$app->session->setFlash('success', 'Profile has been successfully updated.');
                    return $this->redirect(['profile', 'id' => $model->id]);
                }
            }
        }

        return $this->render('profile', [
            'model' => $model,
        ]);

    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Testimonial;
use frontend\components\ClientMindBodyApi;
use frontend\models\Country;
use frontend\models\SalsaLessonForm;
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use frontend\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup','register','client-login'],
                'rules' => [
                    [
                        'actions' => ['signup','register','client-login'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $testimonials = Testimonial::find()->where(['status' => 1])->limit(3)->all();
        return $this->render('index',[
            'testimonials' => $testimonials
        ]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        return $this->redirect(['site/index?type=login']);
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success',
                    'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionLocation()
    {
        return $this->render('location');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionClientLogin()
    {
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            if(Yii::$app->session->has('checkout_class')) {
                return $this->redirect(['/checkout/'.Yii::$app->session->get('checkout_class').'?confirm=1']);
            } elseif(Yii::$app->session->has('checkout_product')) {
                return $this->redirect(['/product-buy/'.Yii::$app->session->get('checkout_product')]);
            }
            return $this->goBack();
        }
        return $this->renderAjax('client-login', [
            'model' => $model,
        ]);

    }

    /***
     * Signup validation
     */
    public function actionAjaxClientLogin()
    {
        $model = new LoginForm();
        $model->load(Yii::$app->request->post());
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = 'json';
            return \yii\widgets\ActiveForm::validate($model);
        }
    }

    public function actionRegister()
    {
        $model = new SignupForm();
        $country = Country::find()->select(['name','iso_code_2'])->all();
        $model->scenario = 'register';
        $errors = false;
        if ($model->load(Yii::$app->request->post())) {
            if($model->BirthDate) {
                $model->BirthDate = date('Y-m-d',strtotime($model->BirthDate));
            }
            $user = $model->signup();
            if ($user) {
                $login = new LoginForm();
                $login->username = $model->Username;
                $login->password = $model->Password;
                $login->login();

                return $this->redirect(['site/index']);
            }
        }

        return $this->render('client-register', [
            'model' => $model,
            'errors' => $errors,
            'country' => $country
        ]);
    }

    /***
     * Signup validation
     */
    public function actionAjaxRegister()
    {
        $model = new SignupForm();
        $model->scenario = 'register';
        $model->load(Yii::$app->request->post());
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = 'json';
            return \yii\widgets\ActiveForm::validate($model);
        }
    }

    public function actionRequest()
    {
        $api = new ClientMindBodyApi();
        $classes = $api->getActivate();;//26663
        //$classes = $api->purchaseClass(10158,50);
        //$classes = $api->getClassDetails(28317);
        //$response = $api->AddClientsToClass(28317);
        print_r($classes);
    }

    public function actionCheckEmail()
    {

        /*$sals = new SalsaLessonForm();
        echo Yii::$app->params['supportEmail'];
        $ap = $sals->sendEmail('tobin@codeatech.com');
        var_dump($ap);*/
    }
    /***
     * Subscriber validation
     */
    public function actionAjaxSubscribe()
    {
        $model = new \common\models\Subscriber;
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post()))
        {
            Yii::$app->response->format = 'json';
            return \yii\widgets\ActiveForm::validate($model);
        }
    }

    /***
     * Subscriber validation
     */
    public function actionSubscribe()
    {
        $model = new \common\models\Subscriber;
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post()))
        {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            if(!$model->save()){
                throw new NotAcceptableHttpException('Something went wrong.Please try again.');
            }
            return [
                'message' => '<div class="alert alert-success">Thank you for subscribing with us.
                                    Please contact us if you have any queries.</div>',
                'code' => 100,
            ];
        }
    }

    public function actionHealcode()
    {
        return $this->render('healcode');
    }

    public function actionSchedule()
    {
        return $this->render('schedule');
    }

    public function actionClassDescription()
    {
        return $this->render('class-description');
    }

    public function actionInstructors()
    {

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/client-login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
?>
<div class="site-login">
    <p>Please fill out the following fields to login:</p>
    <div class="row">
        <div class="col-lg-12">
            <?php $form = ActiveForm::begin([
                'id' => 'login-client-form',
                'action' => Url::to(['site/client-login']),
                'enableAjaxValidation' => true,
                'validationUrl' => Url::to(['site/ajax-client-login']),
            ]); ?>
                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                    <?= Html::a('Register', Url::to(['site/register']),['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/client-register.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Register';
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => 'javascript:void(0)'];
?>
<section class="contact_us">
    <div class="container">
        <div class="row">

            <div class="col-md-7 contact-left reg-fm">
                <h3>Don't have an account?</h3>
                <script src="https://widgets.healcode.com/javascripts/healcode.js" type="text/javascript"></script>

                <healcode-widget data-type="registrations" data-widget-partner="mb" data-widget-id="b56210f24b" data-widget-version="0.1"></healcode-widget>
            </div><!--col-md-5-->

            <div class="col-md-4 contact-right pull-right">
                <h3>Address</h3>

                <p>
                    3550 San Pablo Dam Road Suite F El Sobrante, CA 94803
                    <span>510-222-6300</span>
                </p>

                <div class="contact-img"><img src="<?= $this->theme->baseUrl; ?>/img/contact-img.jpg"
                                              class="img-responsive" alt=""/></div>
            </div><!--col-md-4 pull-right-->

        </div><!--row-->
    </div><!--container-->
</section>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => 'javascript:void(0)'];
?>
<section class="contact_us">
    <div class="container">
        <div class="row">

            <div class="col-md-7 contact-left reg-fm">

                <h3>Contact Us</h3>
                <div class="input-success">
                    <?php if(Yii::$app->session->hasFlash('success')): ?>
                        <div class="alert alert-success" role="alert">
                            <?= Yii::$app->session->getFlash('success') ?>
                        </div>
                    <?php endif; ?>
                </div>
                <p>
                    Have a question, comment or suggestion? We'd love to hear from you! Please use the contact form and we will reply as soon as possible!
                </p>

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true, 'placeholder' => 'Enter Your Name']) ?>

                <?= $form->field($model, 'email')->textInput([ 'placeholder' => 'Enter Email Address']) ?>

                <?= $form->field($model, 'phone')->textInput([ 'placeholder' => 'Enter Phone Number']) ?>

                <?= $form->field($model, 'body')->textArea(['rows' => 6, 'placeholder' => 'Message']) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-default', 'name' => 'contact-button']) ?>
                </div>

                <?php ActiveForm::end(); ?>
            </div><!--col-md-5-->

            <div class="col-md-4 contact-right pull-right">
                <h3>Address</h3>
                <p>
                    3550 San Pablo Dam Road Suite F El Sobrante, CA 94803
                    <span>510-222-6300</span>
                </p>
                <div class="contact-img"><img src="<?= $this->theme->baseUrl; ?>/img/contact-img.jpg" class="img-responsive" alt=""/></div>
            </div><!--col-md-4 pull-right-->

            <div class=" col-sm-12 location_map">
                <div class="location-map-hd">Location Map</div><!--location-map-hd-->
                <div class="map">
                    <div id="map-canvas">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d786.401282711831!2d-122.319873!3d37.963005!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2s!4v1461061211359" width="100%" height="100%" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div><!--map-canvas-->
                </div><!--map-->
            </div><!--location map-->

        </div><!--row-->
    </div><!--container-->
</section>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<section class="S-rental">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="dv-h3"><?php //Html::encode($this->title) ?></div>
                <div class="dv-h3">
                    <?= nl2br(Html::encode($message)) ?>
                </div>
                <p>
                    The above error occurred while the Web server was processing your request.
                </p>
                <p>
                    Please contact us if you think this is a server error. Thank you.
                </p>
            </div><!--col-sm-12-->


        </div><!--row-->
    </div><!--container-->
</section><!--S-rental-->

frontend/views/site/healcode.php
<section class="contact_us">
    <div class="container">
        <div class="row">

            <div class="col-md-7 contact-left reg-fm">
                <h3>Don't have an account?</h3>
                <script src="https://widgets.healcode.com/javascripts/healcode.js" type="text/javascript"></script>

                <healcode-widget data-type="registrations" data-widget-partner="mb" data-widget-id="b56210f24b" data-widget-version="0.1"></healcode-widget>
            </div><!--col-md-5-->

            <div class="col-md-4 contact-right pull-right">
                <h3>Address</h3>

                <p>
                    3550 San Pablo Dam Road Suite F El Sobrante, CA 94803
                    <span>510-222-6300</span>
                </p>

                <div class="contact-img"><img src="<?= $this->theme->baseUrl; ?>/img/contact-img.jpg"
                                              class="img-responsive" alt=""/></div>
            </div><!--col-md-4 pull-right-->

        </div><!--row-->
    </div><!--container-->
</section>
<!--var validWidgetTypes = ['schedules', 'enrollments', 'staff_lists', 'class_lists', 'prospects', 'registrations', 'appointments'];-->

frontend/views/site/location.php
<?php
/* @var $this yii\web\View */

$this->title = 'Location';
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => 'javascript:void(0)'];
?>
<section class="contact_us">
    <div class="container">
        <div class="row">

            <div class="col-md-7 contact-left">
                <h3>Address</h3>
                <p>
                    3550 San Pablo Dam Road Suite F El Sobrante, CA 94803
                    510-222-6300
                </p>
            </div><!--col-md-5-->



            <div class=" col-sm-12 location_map">
                <div class="location-map-hd">Location Map</div><!--location-map-hd-->
                <div class="map">
                    <div id="map-canvas">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d786.401282711831!2d-122.319873!3d37.963005!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2s!4v1461061211359" width="100%" height="100%" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div><!--map-canvas-->
                </div><!--map-->
            </div><!--location map-->

        </div><!--row-->
    </div><!--container-->
</section>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/register.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\UserProfile */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="form-group">
    <?php $form = ActiveForm::begin([
            'id' => 'register-client-form',
            'action' => Url::to(['site/register']),
            'enableAjaxValidation' => true,
            'validationUrl' => Url::to(['site/ajax-register']),
        ]);
    ?>
    <div class="input-success"></div>
    <div id="signup-content">
        <?= $form->field($model, 'username')->textInput(['maxlength' => true,'class'=>'form-control']); ?>
        <?= $form->field($model, 'email')->textInput(['maxlength' => true,'class'=>'form-control']); ?>
        <div class="input-group">
            <?= yii\helpers\Html::submitButton('Submit', ['class' => 'common-btn btn btn-info']) ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/schedule.php
<section class="contact_us">
    <div class="container">
        <div class="row">

            <div class="col-md-12 contact-left reg-fm">
                <script src="https://widgets.healcode.com/javascripts/healcode.js" type="text/javascript"></script>

                <healcode-widget data-type="schedules" data-widget-partner="mb" data-widget-id="b512220f24b" data-widget-version="0.1"></healcode-widget>
            </div>

        </div><!--row-->
    </div><!--container-->
</section>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>